---
title: "Assignment-5"
author: "Jiwon Park"
date: '2020 10 2 '
output: html_document
---

```{r setup, include = FALSE}
knitr:: opts_chunk$set(echo = TRUE)
```

## Load Libraries
```{r message = FALSE}
library(osmdata)
library(opentripplanner)
library(tidyverse)
library(sf)
library(ggthemes)
library(ggplot2)
library(raster)
library(ggspatial)
library(tidygeocoder)
library(rgdal)
```

## Load locations
```{r}
poll_location <- st_read(
"http://bostonopendata-boston.opendata.arcgis.com/datasets/f7c6dc9eb6b14463a3dd87451beba13f_5.kml?outSR=%7B%22latestWkid%22%3A2249%2C%22wkid%22%3A102686%7D")
```

## Get street data

```{r}
opq(bbox = 'Cambridge MA USA') %>%
  add_osm_feature(key = 'highway') %>%
  osmdata_xml(file = 'OTP/graphs/default/cambridge_streets.osm')
```


```{r}
MA_state_plane <- "+proj=lcc +lat_1=41.71666666666667 +lat_2=42.68333333333333 +lat_0=41 +lon_0=-71.5 +x_0=200000 +y_0=750000 +ellps=GRS80 +units=m +no_defs"

cambridge_street_features <- opq(bbox = 'Cambridge MA USA') %>%
  add_osm_feature(key = 'highway') %>%
  osmdata_sf()

cambridge_streets <- cambridge_street_features$osm_lines %>%
  st_transform(crs = MA_state_plane)
```


```{r}
ggplot(cambridge_streets) + 
  geom_sf() + 
  theme_map()
```

## Set up Open Trip Planner

```{r}
path_otp <- otp_dl_jar("OTP")
```

```{r, message = FALSE, results = 'hide'}
path_data <- file.path(getwd(), "OTP")
path_otp <- paste(path_data, "otp.jar",sep = "/")

otp_build_graph(otp = path_otp, dir = path_data, memory = 1024) 
```

```{r}
otp_setup(otp = path_otp, dir = path_data, memory =1024)
otpcon <- otp_connect()
```

## Create Isochrone for area within a five-minute walk and bicycling

```{r, message = FALSE, results = 'hide'}
iso_5min_walk <- 
  otp_isochrone(otpcon = otpcon, 
                fromPlace = poll_location, 
                mode = "WALK", 
                cutoffSec = 300) %>%
  st_transform(crs = MA_state_plane) %>%
  mutate(mode = "walk")

iso_5min_bike <- 
  otp_isochrone(otpcon = otpcon, 
                fromPlace = poll_location, 
                mode = "BICYCLE", 
                cutoffSec = 300) %>%
  st_transform(crs = MA_state_plane) %>%
  mutate(mode = "bike")

iso_all_modes <- rbind(iso_5min_walk, iso_5min_bike)
```

```{r}
ggplot(iso_all_modes) +
  geom_sf(data = cambridge_streets, color = "gray") +
  geom_sf(aes(fill = mode), alpha = 0.5) +
  geom_sf(data = poll_location) +
  coord_sf(xlim = c(left_side, right_side), 
           ylim = c(bottom_side, top_side), expand = FALSE) +
  scale_fill_viridis_d(name = "Area that is reachable within 5 minutes") +
  theme_map() 
```

## Calcuate and compare isochrone areas (1)

```{r}
iso_areas <- iso_all_modes %>%
  mutate(area = st_area(iso_all_modes)) %>%
  st_set_geometry(NULL) %>%
  pivot_wider(names_from = mode, values_from = area) 

ggplot(iso_areas, 
       aes(x = as.numeric(bike), y = as.numeric(walk))) +
  geom_point() +
  scale_x_continuous(name = 
            "Area within a five-minute walking distance\nof a polling station\n(square km)",
            breaks = breaks <- seq(10000, 130000, by = 20000),
            labels = breaks / 1000000) +
  scale_y_continuous(name = 
            "Area within a five-minute bicycling distance\nof a polling station\n(square km)",
            breaks = breaks <- seq(0, 700000, by = 100000),
            labels = breaks / 1000000) +
  theme_bw()
```

